name: Build Linux Kernel Debian Package

on:
  workflow_dispatch:  # 手动触发工作流
  push:
    branches: [ main ]  # 在推送到 main 分支时自动运行

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential flex bison libssl-dev libelf-dev bc lz4 rsync curl wget git fakeroot debhelper

      - name: Download kernel config file
        run: |
          mkdir -p kernel-build
          cd kernel-build
          wget -O .config https://raw.githubusercontent.com/huifujing/amd-kernel-6.14.0/main/config-6.1.0-32-amd64
          if [ $? -ne 0 ]; then
            echo "Failed to download config file"
            exit 1
          fi

      - name: Clone Linux kernel repository
        run: |
          git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux-6.14
          if [ $? -ne 0 ]; then
            echo "Failed to clone kernel repository"
            exit 1
          fi

      - name: Prepare build environment
        run: |
          cp kernel-build/.config linux-6.14/
          cd linux-6.14
          make olddefconfig

      - name: Build kernel Debian packages
        run: |
          cd linux-6.14
          make -j$(nproc) deb-pkg
          
      - name: Upload Debian packages
        uses: actions/upload-artifact@v3
        with:
          name: kernel-debs
          path: |
            linux-*.deb
            
      - name: Generate package info
        run: |
          ls -la *.deb > package-info.txt
          
      - name: Upload package info
        uses: actions/upload-artifact@v3
        with:
          name: package-info
          path: package-info.txt
