name: Compile Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update and install dependencies
      run: |
        sudo apt update
        sudo apt install -y wget curl gnupg2 
        sudo apt update && sudo apt upgrade -y
        sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc dwarves
        sudo apt install -y git python3
        sudo apt install -y sudo wget curl nload screen nftables cron expect zip snapd
        sudo apt install -y debhelper rsync

    - name: Clone latest kernel source code
      run: |
        cd /usr/src
        sudo git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git linux-6.14

    - name: Compile the kernel
      run: |
        cd /usr/src/linux-6.14
        sudo chmod 777 /usr/src/linux-6.14
        sudo wget https://github.com/huifujing/amd-kernel-6.14.0/blob/main/config-6.1.0-32-amd64 -O /usr/src/linux-6.14/config-6.1.0-32-amd64
        printf "\n" | sudo make oldconfig
        sudo make -j$(nproc) deb-pkg

    - name: Upload the artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        name: kernel-debs
        path: /usr/src/*.deb
