name: Compile Kernel
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update and install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc dwarves git python3 wget curl
        
    - name: Clone latest kernel source code
      run: |
        sudo mkdir -p /usr/src
        sudo git clone --depth=1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git /usr/src/linux-6.14
        
    - name: Configure and compile the kernel
      run: |
        cd /usr/src/linux-6.14
        sudo chmod 777 /usr/src/linux-6.14
        # Use default configuration as a starting point
        sudo make defconfig
        # Customize configuration if needed (optional)
        # sudo make menuconfig
        # Build debian packages
        sudo make -j$(nproc) deb-pkg
        
    - name: Upload the artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-debs
        path: /usr/src/*.deb
